#!/usr/bin/env bash
# comments go here!
# trap: receive signal
echo $$ >> /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
